# Generated by Django 3.0.8 on 2020-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdr', models.CharField(choices=[('yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('technical_name', models.CharField(max_length=200)),
                ('creation_date', models.DateField(verbose_name='day entered service')),
                ('weight', models.IntegerField()),
                ('rate_fire', models.IntegerField()),
                ('ammo_capacity', models.IntegerField()),
                ('currently_in_use', models.BooleanField()),
            ],
        ),
    ]
