# Generated by Django 3.0.8 on 2020-08-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand_carried_guns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='hdr',
        ),
    ]
