# Generated by Django 3.0.8 on 2020-08-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand_carried_guns', '0002_remove_weapon_hdr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='rate_fire',
            new_name='rate_of_fire',
        ),
    ]
