# Generated by Django 3.0.8 on 2020-08-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_carried_guns', '0003_auto_20200809_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
