# Generated by Django 3.0.8 on 2020-08-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_carried_guns', '0004_weapon_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weight',
            field=models.FloatField(),
        ),
    ]
