# Generated by Django 3.0.8 on 2020-08-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_carried_guns', '0005_auto_20200816_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='creation_date',
            field=models.DateField(verbose_name='Entered service'),
        ),
    ]
