# Generated by Django 3.0.8 on 2020-10-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_carried_guns', '0006_auto_20200823_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
